DEFAULT_MODULE += auto_init_at86rf233
DEFAULT_MODULE += netdev_ieee802154_oqpsk

USEMODULE += at86rf2xx_common
USEMODULE += at86rf2xx_spi

FEATURES_REQUIRED += periph_gpio
FEATURES_REQUIRED += periph_gpio_irq
FEATURES_REQUIRED += periph_spi

ifneq (,$(filter at86rf233_aes,$(USEMODULE)))
  USEMODULE += at86rf2xx_common_aes_spi
endif
